#!/bin/bash
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
# OpenClaw Cloud 2026 - EXACT DEPLOYMENT COMMANDS
# â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

echo "ðŸ“‹ OpenClaw Cloud 2026 - Deployment Command Reference"
echo "======================================================"
echo ""

echo "ðŸ” STEP 1: Get Pickaxe API Key"
echo "   Go to: https://pickaxe.ai"
echo "   Sign up (free tier)"
echo "   Copy your API key (format: pk-xxxxx)"
echo ""

echo "âœï¸  STEP 2: Update Environment Variables"
echo ""
echo "   Edit .env file:"
echo "   $ nano .env"
echo ""
echo "   Update these lines:"
echo "   PICKAXE_API_KEY=DEPRECATED_MIGRADO_A_GEMINI"
echo "   DB_PASSWORD=generate-secure-password"
echo "   REDIS_PASSWORD=generate-secure-password"
echo "   SECRET_KEY=generate-random-string"
echo ""

echo "Generate secure values:"
echo "   $ openssl rand -base64 32"
echo ""

echo "ðŸš€ STEP 3: Deploy with Docker Compose"
echo ""
echo "   Option A - Automatic (Linux/macOS):"
echo "   $ chmod +x scripts/deploy-cloud.sh"
echo "   $ ./scripts/deploy-cloud.sh"
echo ""
echo "   Option B - Automatic (Windows PowerShell):"
echo "   $ .\scripts\deploy-cloud.ps1"
echo ""
echo "   Option C - Manual (Any OS):"
echo "   $ docker-compose up -d --build"
echo ""

echo "â³ STEP 4: Wait for Services to Start"
echo "   $ sleep 30"
echo ""

echo "âœ… STEP 5: Verify Deployment"
echo ""
echo "   Check services:"
echo "   $ docker-compose ps"
echo ""
echo "   Health check:"
echo "   $ curl http://localhost:8080/health"
echo ""
echo "   MCP Status:"
echo "   $ curl http://localhost:8080/api/mcp/status"
echo ""
echo "   Test chat:"
echo "   $ curl -X POST http://localhost:8080/api/mcp/message \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"agent\":\"main\",\"message\":\"Hello OpenClaw\"}'"
echo ""

echo "ðŸŒ STEP 6: Access Your Deployment"
echo ""
echo "   Local Machine:"
echo "   â€¢ UI: http://localhost"
echo "   â€¢ API: http://localhost:8080/api"
echo "   â€¢ Chat: http://localhost/chat"
echo ""
echo "   Cloud Deployment (with domain):"
echo "   â€¢ UI: https://your-domain.com"
echo "   â€¢ API: https://your-domain.com/api"
echo "   â€¢ Chat: https://your-domain.com/chat"
echo ""

echo "ðŸ› ï¸  USEFUL COMMANDS"
echo ""
echo "   View all containers:"
echo "   $ docker-compose ps"
echo ""
echo "   View logs (follow mode):"
echo "   $ docker-compose logs -f"
echo ""
echo "   View specific service logs:"
echo "   $ docker-compose logs -f openclaw_app"
echo ""
echo "   Stop all services:"
echo "   $ docker-compose down"
echo ""
echo "   Stop and remove all data:"
echo "   $ docker-compose down -v"
echo ""
echo "   Restart a service:"
echo "   $ docker-compose restart openclaw_app"
echo ""
echo "   Execute command in container:"
echo "   $ docker-compose exec openclaw_app bash"
echo ""
echo "   Check resource usage:"
echo "   $ docker stats"
echo ""

echo "â˜ï¸  CLOUD PROVIDER DEPLOYMENTS"
echo ""
echo "   AWS ECS:"
echo "   1. Create ECR repository"
echo "   2. Build and push images"
echo "   3. Create ECS task definition"
echo "   4. Deploy service"
echo "   â†’ See DEPLOYMENT_GUIDE.md for full instructions"
echo ""
echo "   Google Cloud Run:"
echo "   $ gcloud run deploy openclaw --source . --platform managed"
echo "   â†’ See DEPLOYMENT_GUIDE.md for full instructions"
echo ""
echo "   DigitalOcean Droplet:"
echo "   1. SSH to droplet"
echo "   2. Install Docker"
echo "   3. Clone project"
echo "   4. Configure .env"
echo "   5. docker-compose up -d"
echo "   â†’ See DEPLOYMENT_GUIDE.md for full instructions"
echo ""

echo "ðŸ”’ PRODUCTION SETUP"
echo ""
echo "   SSL/TLS Setup:"
echo "   $ certbot certonly --standalone -d your-domain.com"
echo "   $ cp /etc/letsencrypt/live/your-domain.com/fullchain.pem nginx/ssl/openclaw.crt"
echo "   $ cp /etc/letsencrypt/live/your-domain.com/privkey.pem nginx/ssl/openclaw.key"
echo "   $ docker-compose restart nginx"
echo ""

echo "ðŸ†˜ EMERGENCY COMMANDS"
echo ""
echo "   If services fail to start:"
echo "   $ docker-compose logs openclaw_app"
echo "   $ docker-compose down -v"
echo "   $ docker-compose up -d --build"
echo ""
echo "   If database fails:"
echo "   $ docker-compose exec db psql -U openclaw_admin -d openclaw_prod -c \"SELECT 1;\""
echo ""
echo "   If out of memory:"
echo "   $ docker system prune -a"
echo "   $ docker-compose restart"
echo ""

echo "ðŸ“š DOCUMENTATION"
echo ""
echo "   Full README:        README.md"
echo "   Deployment Guide:   DEPLOYMENT_GUIDE.md"
echo "   Quick Reference:    QUICK_REFERENCE.md"
echo "   This file:          COMMANDS.sh"
echo ""

echo "======================================================"
echo "âœ… Ready to deploy OpenClaw Cloud 2026!"
echo "======================================================"

