# Usa una imagen ligera de Python
FROM python:3.11-slim

# Define el directorio de trabajo
WORKDIR /gateway

# Copia dependencias
COPY requirements.txt .

# Instala dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código del gateway
COPY . .

# Expone el puerto 8080
EXPOSE 8080

# Arranque con Gunicorn apuntando al gateway
CMD ["gunicorn", "-b", "0.0.0.0:8080", "gateway:app"]
