
services:
  app:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    command: python webhook_globy.py
    networks:
      - internal

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    volumes:
      - .:/gateway
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "8080:8080"

  gateway_alt:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    volumes:
      - .:/gateway
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "8081:8080"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: oc_user
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: oc_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_data:
